Update  pascalsTriangleRows to allow nullable type
The current version of `pascalTriangleRows` has an `int` type declaration for its parameter `$rowCount`, but this causes one of the unit tests to fail:

```
There was 1 error:

1) PascalsTriangleTest::testNullNoRows
TypeError: pascalsTriangleRows(): Argument #1 ($rowCount) must be of type int, null given
```

Marking it as nullable results in all unit tests passing.